### ISSUE TITLE
Username is not unique

### ISSUE THREAD

**Issue by VictorWinberg** [VictorWinberg/eitf05#24]
Right now I can make another account with same username as another user, which will make me log into the other user account.

We need to make some values unique in [init.sql](https://github.com/VictorWinberg/eitf05/blob/master/sql/init.sql)
- `username` in `Users`
- `name` in `Items` ?

Then we need to handle this in [sign-up.php](https://github.com/VictorWinberg/eitf05/blob/master/public_html/sign-up.php)

**Comment by tovesson** [comment]
I've made username and name UNIQUE
