### ISSUE TITLE
Sign-up needs htmlspecialchars

### ISSUE THREAD

**Issue by VictorWinberg** [VictorWinberg/eitf05#25]
When inserting into sql we need to `htmlspecialchars` the values first, to avoid `<script>...</script>`-tags.

We also insert in `payment.php` but I guess there is no need for that there? Because the user cant change the `userId` or `itemId`, right?

**Comment by HannaLindwall** [comment]
Doing it for all values

**Comment by VictorWinberg** [comment]
This issue will automatically be close when PR #29 is merged.
